"""Add service ticket details fields

Revision ID: 1d3e01ac9024
Revises: ed652f518bce
Create Date: 2026-01-08 21:36:12.066666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3e01ac9024'
down_revision = 'ed652f518bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odometer_reading', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description_of_issue', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('work_performed', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('estimated_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.drop_column('final_cost')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('work_performed')
        batch_op.drop_column('description_of_issue')
        batch_op.drop_column('odometer_reading')

    # ### end Alembic commands ###
