"""Add password to mechanic

Revision ID: bd685ea1ab69
Revises: 1d3e01ac9024
Create Date: 2026-01-10 02:09:43.571603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd685ea1ab69'
down_revision = '1d3e01ac9024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
